#!/usr/bin/env bash
BACKUP_DIR="/tmp/$(date +"%B-%d-%Y_%T")"
BACKUP_ZIP="/tmp/$(basename ${BACKUP_DIR}).zip"
source config

echo Backup being constructed in this folder: ${BACKUP_DIR}
rm -rf ${BACKUP_DIR}
mkdir ${BACKUP_DIR}

for i in "${BACKUP_DBs[@]}"
do
	echo Backing up MySQL DB: ${i}
	mysqldump -u backup_user ${i} > ${BACKUP_DIR}/${i}_mysql.sql
done

for i in "${BACKUP_FOLDERS[@]}"
do
	echo Backing up folder: ${i}
	cd ${i}/..; zip -rq ${BACKUP_DIR}/$(basename ${i}).zip $(basename ${i}) 
done

echo Zipping up collected archive in ${BACKUP_ZIP}
cd ${BACKUP_DIR}/..; zip -rq ${BACKUP_ZIP} $(basename ${BACKUP_DIR})
gdrive upload --delete ${BACKUP_ZIP}
rm -rf ${BACKUP_DIR}
